export default class ActionTypes {

    static USER_SIGNUP = "USER_SIGNUP";
    static USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
    static USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

    static GET_TODO = "GET_TODO";
    static GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
    static GET_TODO_FAIL = "GET_TODO_FAIL";
    
    static ADD_TODO = "ADD_TODO";
    static ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
    static ADD_TODO_FAIL = "ADD_TODO_FAIL";

    static UPDATE_TODO = "UPDATE_TODO";
    static UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
    static UPDATE_TODO_FAIL = "UPDATE_TODO_FAIL";

    static DELETE_TODO = "DELETE_TODO";
    static DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
    static DELETE_TODO_FAIL = "DELETE_TODO_FAIL";

    static USER_ERROR_UPDATE = "USER_ERROR_UPDATE";
}